# Zypher Chatbot
# Created by: [Your Name]

import streamlit as st
from transformers import pipeline
import speech_recognition as sr
import pyttsx3
import requests

# Page Configurations
st.set_page_config(page_title="Zypher Chatbot", layout="centered")

# Custom CSS for minimalistic UI
st.markdown(
    """<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f9;
        color: #333;
    }
    .stButton > button {
        background-color: #007bff;
        color: white;
        border-radius: 5px;
        padding: 5px 10px;
    }
    </style>""",
    unsafe_allow_html=True
)

# Sidebar Navigation
st.sidebar.title("Zypher Chatbot")
page = st.sidebar.radio("Navigate", ["Text Response", "Voice Recognition", "Image Generation"])

# Global Variables
text_generator = pipeline("text-generation", model="gpt2")
recognizer = sr.Recognizer()
engine = pyttsx3.init()

# Page 1: Text Response
def text_response():
    st.title("Zypher - Text Response")
    user_input = st.text_area("Enter your message:")
    if st.button("Send"):
        with st.spinner("Zypher is thinking..."):
            response = text_generator(user_input, max_length=50, num_return_sequences=1)
            st.success(response[0]['generated_text'])

# Page 2: Voice Recognition
def voice_recognition():
    st.title("Zypher - Voice Recognition")
    st.info("Click the button below and speak to Zypher.")
    if st.button("Speak"):
        with sr.Microphone() as source:
            st.write("Listening...")
            try:
                audio = recognizer.listen(source, timeout=5)
                text = recognizer.recognize_google(audio)
                st.write("You said:", text)
                with st.spinner("Zypher is responding..."):
                    response = text_generator(text, max_length=50, num_return_sequences=1)
                    st.success(response[0]['generated_text'])
                    engine.say(response[0]['generated_text'])
                    engine.runAndWait()
            except Exception as e:
                st.error("Could not process your voice input: " + str(e))

# Page 3: Image Generation
def image_generation():
    st.title("Zypher - Image Generation")
    user_prompt = st.text_input("Describe the image you want to generate:")
    if st.button("Generate Image"):
        with st.spinner("Zypher is creating your image..."):
            try:
                response = requests.post(
                    "https://api.deepai.org/api/text2img",
                    data={'text': user_prompt},
                    headers={'api-key': 'YOUR_API_KEY'}
                )
                image_url = response.json()["output_url"]
                st.image(image_url, caption="Generated by Zypher")
            except Exception as e:
                st.error("Image generation failed: " + str(e))

# Render Pages
if page == "Text Response":
    text_response()
elif page == "Voice Recognition":
    voice_recognition()
elif page == "Image Generation":
    image_generation()

# Footer
st.sidebar.markdown("---")
st.sidebar.text("Zypher Chatbot")
st.sidebar.text("Created by: [Your Name]")
